handlers.helloWorld_Custom = function (args) {

    // "currentPlayerId" is initialized to the PlayFab ID of the player logged-in on the game client. 
    // Cloud Script handles authenticating the player automatically.
    
    var user = server.GetUserData({
        PlayFabId: currentPlayerId
    });
    
    var message = "kick ass!!! " + currentPlayerId + "!!! " + user.PlayFabId + " ,,, data: " + user.data;
    //var message = "kick ass!!! " + currentPlayerId + "! ,, " + updateUserDataResult;

    // You can use the "log" object to write out debugging statements. The "log" object has
    // three functions corresponding to logging level: debug, info, and error.
    log.info(message);

    // Whatever value you return from a CloudScript handler function is passed back 
    // to the game client. It is set in the "Results" property of the object returned by the 
    // RunCloudScript API. Any log statments generated by the handler function are also included 
    // in the "ActionLog" field of the RunCloudScript result, so you can use them to assist in
    // debugging and error handling.
    return { messageValue: message };
}